
* Introducción (Capitulo 1)

** Sumario2
- La tecnología web surge como la solución a una necesidad de crear sistemas sencillos para poder compartir información, desde la misma concepción de esta tecnología la parte de comunicación es fundamental
- Sin embargo no solo es información, sino como es que se presenta y es ahí donde surge el termino de el dinseño en las interfaces, este diseño que tiene mucha relevancia
- Para terminar en como es que se pueden aplicar estos conceptos y tecnologías

- La tecnología web surge como una necesidad para poder intercambiar información de una manera sencilla y eficiente
- A lo largo de los años ha ido evolucionando
- Pasando de la creación de páginas web estáticas a poder crear aplicaciones de nivel de producción super dinámicas y completas
- Durante la evolución de la tecnología web se vió que no solo era importante la información sino como se presentaba esta
- Es ahí donde toma relevancia el diseño gráfico en la creación de interfaces, lo cual evolucionó completamente como entendíamos las interfaces
- Con la flexibilidad que las tecnologías web les permitian a los desarrolladores y diseñadores se empezó a experimentar con cosas que nadie se hubiera imaginado
- Así que con la creciente mejora y estandarización de las tecnologías web además de la aplicación de tecnicas avanzadas de interfaces graficas ahora es posible crear aplicaciones de un gran nivel tanto gráfico como de funcionalidad utilizando estas tecnologías
- Esto se puede aplicar a un sin numero de cosas sin embargo en el area de la creación de interfaces para robots no ha sido muy utilizado,
- Para poder explorar su uso y aplicación en la robótica primero debemos entender como es que funcionan estás tecnologías

- El desarrollo web en estos momentos está en boca de todos

*** En los tiempos antes del internet no exitían maneras eficientes de compartir información, fue así que un grupo de investigadores en el CERN decidieron crear un sistema de intercambio de información eficiente basado en un protocolo y que garantizara que la información fuera mandada sin errores. Fueron estas investigaciones las que llevaron a la creación de lo qu ehoy conocemos como internet, desde la creación del protocolo tcp/ip, hasta el el lenguaje HTML que ayudaba a darle forma al contenido que se transmitía. Estás fueron las primeras tecnologías web, sin embargo con el paso de los años fue evolucionando adaptandose a las necesidades de la sociedad y aprovechando las nuevas ventajas tecnologicas. Fue así como además surgió el lenguaje CSS, javascript, PHP, AJAX, y así un sinfin de tecnologíás.

*** Todas ellas han demostrado varias características importantes que las han hecho extremadamente populares, y no solo eso sino también flexibles, no están limitadas a un sistema operativo, o a un esquema de interfaces. Esto llevo a que no solo rompiera paradigmas a la hora de comunicar información sino también a cambiar la manera en la que se entienden las interfaces, se experimentó con nuevos diseños, se le dió gran prioridad a la experiencia de usuario, y surgió toda una nueva area a la hora de crear experiencias de usuario.

*** Sin embargo durante un tiempo estas tecnologías solo estuvieron presentes en el desarrollo de páginas web, pero ha sido con  cambios recientes que le han dado gran poder a las aplicaciones web de tal manera que al día de hoy pueden competir con aplicaciones nativas pero con todas las ventajas que siguen teniendo las aplicaciones web. Se han creado desde aplicaciones que pueden tomar notas sencillas, guardarlas y que se pueden ver desde cualquier lugar con internet. Hasta entornos completos para oficina, herramientas de dibujo avanzadas, software científico etc. En las que han logrado mostrar grandes avances y ventajas sobre otros desarrollos similares. Es cierto que todavía no llegan a un nivel de integración tal que puedan reemplazar en todos los aspectos a las aplicaciones nativas pero sus ventajas resultan mejores en muchos casos.

*** A pesar del éxito que han tenido el desarrollo de aplicaciones web en diferentes áreas, en el area de la robótica no ha sido utilizado tanto, al menos en la facultad de ingeniería de la UNAM, así que en los siguientes cápitulos se explorarán el estado actual de las tecnologías web para después proponer algunas que ayuden particularmente a los proyectos de robótica creando proyectos que puedan ayudar en diferentes fases del desarrollo.

*** [#A]

Hoy en día todos conocemos la tecnologíá web y la utilizamos todo el tiempo, ya sea para el correo electrónico, mapas, comprar cosas, entre muchas otras, sin embargo no siempre fue algo tan común. La tecnología web nació como solución  para poder compartir información entre investigadores de manera eficiente, el correo electrónico tenía limitaciones y se necesitaba un sistema que permitiera ser más gráfico, muchas personas pudieran ver y se pudiera actualizar constantemente. Es así como en el CERN en el año de 1982 desarrollaron las primeras tecnologías web, las cuales siguen siendo un pilar para el internet, el protocolo TCP y el lenguaje declarativo HTML. Es grande la evolución que ha tenido la web desde sus inicios en el CERN pero sin duda se ha convertido en una parte fundamental del desarrollo tecnologíco actual.

La web ha cambiado la forma en la que interactuamos con la tecnología, creando interfaces dinámicas, que se pueden utilizar en cualquier lugar, enfocandose en la experiencia de usuario. La web ha evolucionado poco a poco y se ha hecho muy versatil y poderosa, tanto así que se han creado aplicaciones tan complejas como herramientas avanzadas de dibujo, sistemas CAD, suites de oficina, entre muchas otras. A pesar de esto en el area de robótica no es tan conocida, poco a poco se ha ido utilizando pero no ha logrado impactar de gran manera. Es posible utilizar esta tecnología de manera eficiente para el desarrollo de interfaces de robótica? 

*** [#B] 

En los tiempos antes del internet no exitían maneras eficientes de compartir información, fue a partir de eso que un grupo de investigadores en el CERN decidieron crear un sistema de intercambio de información eficiente. Desarrollaron un protocolo de comunicación llamado TCP y un lenguaje descriptivo llamado HTML, estás fueron las primeras tecnologías web, sin embargo con el paso de los años fue evolucionando adaptandose a las necesidades de la sociedad y aprovechando las nuevas ventajas tecnológicas, fue así como además surgió el lenguaje CSS, javascript, PHP, AJAX, entre muchas otras.

La tecnología web fue aumentando rápidamente en popularidad, en gran medida gracias al creciente uso de internet y la cada vez mejor implementación de estandares. Se fueron agregando cada vez más funciones, lo que hizo que se pudieran desarrollar aplicaciones web, las cuales ya no solo eran páginas estáticas de información sino aplicaciones completas que interactuaban con los usuarios de forma dinámica. Además debido a la versatilidad a la hora de construir la parte gráfica y de interacción las interfaces empezaron a experimentar con diferentes formas de interfaces y experiencia de usuario.

Con esta tecnología web madura se empezatron a desarrollar

** The rising of the web technology
- La historia de la tecnolgía web, como inició, mencionar características sobre las tecnologías base que se utilizaron desde el inicio, HTTP, HTML, CSS, Javascript, sobre la naturaleza que se tiene para comunicación, como fue mejorando con el tiempo agregandosele nuevas caracteristicas y como fue la evolución de las aplicaciones web, desde las páginas estáticas con gif hasta google drive que es una aplicación completa, mostrar ejemplos de aplicaciones de estás tecnologías, vestibles, internet de las cosas etc

*** La tecnología web comprende muchas tecnologías que funcionan de manera simultanea para poder crear lo que conocemos como interfaces web, las cuales se comunican de maneras diferentes con los procesos externos con los que se están trabajando.

*** 

** Interfaces gráficas

** Y los robots?, 
- El desarrollo robótico y las interfaces, como desde un inicio la robótica ha estado ligada con las interfaces que se utilizan, historia de las interfaces en los robots y algunos ejemplos
